### PR TITLE
Excluding indexing of pages

### PR DESCRIPTION
**Pull request by qWici**
- [x] Make an important contribution to the development of the project :laughing:

### CODE REVIEW

**Comment by mustardandrew** [comment]
tomorrow...

**Comment by mustardandrew** [comment]
Error in code
```html
<meta name="robots" content="noindex, nofollow"
```

**Comment by mustardandrew** [comment]
It's not a critical :no_good_man:

**Comment by qWici** [comment]
@mustardandrew critical in this case

**Pull request merged**
